baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Fusion CAC Documentation'
theme = 'relearn'

[params]
themeVariant = 'zen-light'


[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ['html', 'rss', 'search']
